trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self

  - script: |
      echo "Listing top-level files"
      ls -1
    displayName: 'Debug: show root directory'

  - task: Maven@3
    displayName: 'Maven build'
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean package'
